export const AUCTION_REPOSITORY_REDIS = Symbol('AUCTION_REPOSITORY_REDIS');
export const AUCTION_PRESENTER = Symbol('AUCTION_PRESENTER');
export const SOCKETIO_NOTIFIER = Symbol('SOCKETIO_NOTIFIER');
